spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestiontransfert?createDatabaseIfNotExist=true
    username: fatimata
    password: passer123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  devtools:
    restart:
      enabled: true   # Active ou désactive le redémarrage automatique
    livereload:
      enabled: true   # Active ou désactive le live reload

  servlet:
    multipart:
      max-file-size: 10MB
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    org.springframework.web: DEBUG
server:
  port: 4080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    oauth2RedirectUrl: /swagger-ui/oauth2-redirect.html
    display-request-duration: true
  show-actuator: true

  security-schemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearer-format: JWT

# application.yml
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000


